### ISSUE TITLE
Update documentation with steps to get Airtable's base ID and table ID

### ISSUE THREAD

**Issue by trancethehuman** [felixbrock/lemon-agent#3]
Maybe include some steps from this guide: https://www.highviewapps.com/kb/where-can-i-find-the-airtable-base-id-and-table-id/

**Comment by felixbrock** [comment]
Good point @trancethehuman, thanks for pointing that out! Resolved by commit [fbf50aa](https://github.com/felixbrock/lemonai-py-client/commit/fbf50aa84ead6fd62b3ad702872b26428167000b)
