### ISSUE TITLE
lemonai.json

### ISSUE THREAD

**Issue by YuuuuuUoU** [felixbrock/lemon-agent#4]
I added lemonai.json but it doesn't work. Is there any detail to pay attention to? For example, where are the files placed

**Comment by felixbrock** [comment]
Hey, @YuuuuuUoU thanks a lot for creating the issue 🙌

The lemonai.json file needs to be placed at the project root. Also, please make sure you are following the json [structure](https://github.com/felixbrock/lemonai/tree/main#optional-define-your-lemon-ai-functions) mentioned in the readme and also make sure to include the right [tool names](https://github.com/felixbrock/lemonai/blob/main/docs/tools.md). 

Simultaneously, I will run some tests on my end and get back to right away!

**Comment by felixbrock** [comment]
Just ran a very simple test. The following case worked for me.  In case you are still facing issues please let me know, more than happy to help!

**test.py**:
```Python
import os
from lemonai import execute_workflow
from langchain import OpenAI

""" Load all relevant API Keys and Access Tokens into your environment variables """
os.environ["OPENAI_API_KEY"] = "***INSERT KEY***"

article_id = "36600966"

""" Define your instruction to be given to your LLM """
prompt = f"""
Execute the workflow 'Get my repository information' with the aticleId {article_id}.
"""

"""
Use the Lemon AI execute_workflow wrapper
to run your LangChain agent in combination with Lemon AI
"""
model = OpenAI(temperature=0)

"""
To use local server include 'server_domain' arg
with localhost address (e.g. 'server_domain='http://localhost:1313')
"""
execute_workflow(llm=model, prompt_string=prompt)
```

**lemonai.json**:
```json
[
  {
    "name": "Get my repository information",
    "description": "Retrieve an article",
    "tools": ["hackernews-get-article"]
  }
]
```
