### ISSUE TITLE
Why is it not actively maintained?

### ISSUE THREAD

**Issue by nahimilega** [felixbrock/lemon-agent#6]
Pretty cool project...

Actually, I was also thinking of building something similar to make calling API easy via LLM...

I saw sadly repo not under active maintenance...
Just wanted to know like what happened.. what's the reason...   any advice..  any issues folks stumbled into causing to not actively maintain this?

**Comment by felixbrock** [comment]
Hey @nahimilega, thanks for reaching out!

It was challenging to make the solution scale to a realistic level of use case complexity. The reliability of Lemon Agent exponentially decreased with each step added to a given workflow that was to be executed by the agent. The main issues lay with input/output transformation by the agents in between workflow steps (e.g. identify relevant fields in the response body of workflow step 3, combine those with response elements of workflow step 2 and transform it to a valid request body that can be used to execute workflow step 4) and the communication between plan, solve and validate agent (internal function calling). Back then we didn’t see how to successfully scale the solution to 1000s of integration points.

What will your solution look like? How are those issues relevant to what you are working on?
